"use client";
import './globals.css'
import { DM_Sans } from 'next/font/google'
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from 'react';
import 'bootstrap/dist/css/bootstrap.min.css';
const dm_sans = DM_Sans({ 
  subsets: ['latin'] ,
  weight:['400', '500']
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  useEffect(() => {
    import("bootstrap/dist/js/bootstrap.bundle.min.js");
  }, []);
  useEffect(() => {
    AOS.init();
  }, []);
  return (
    <html lang="en">
      <body className={dm_sans.className}>{children}</body>
    </html>
  )
}
