
export const CareerDataDetails = [
    {
      id: 1,
      title: "Director of Business Development",
      slug: "Director-of-Business-Development",
      dis1: `We appreciate your interest in joining the team at Ethereum Address Service (EAS) as a Business Development Development. EAS is mapping the world’s addresses as tradable NFTs. With EAS, real-world addresses become transactable digital address rights designed to generate revenue from their commercial use in Web3 and the metaverse. We envision a future where every real-world address and point of interest has an associated EAS NFT. EAS serves as the platform to monetize and manage these new digital address rights and drive price appreciation for NFT buyers.`,
      dis2: `As a Business Development Director with EAS, your responsibilities will include:`,
      dis3: `The EAS Business Development Director is a remote position and all required assignments are completed virtually. We DO NOT require physical attendance at an office location. The Business Development Director is a commission-based position with the opportunity for salary and additional compensation on a case-by-case basis.`,
      dis4: `To be eligible for this opportunity we would ask that you formally apply through Smart Recruiters. We look forward to meeting you and considering you for the EAS team.`,
      dis5: `Best regards, `,
      dis6: `The EAS Team`,
      itemList1:` –   Responsibilities will include the management of regional sales team/s in your assigned geographical region.`,
      itemList2:` –  Responsibilities will include generating new corporate partnerships.`,
      itemList3:` – Responsibilities will include the management of regional sales team/s in your assigned geographical region.`,
      itemList4:` – Responsibilities will include research of target buyers and crafting outreach communications to initiate introductory dialogue with prospective institutional buyers and crypto & NFT companies.`,
      date: "March 17, 20023",
      job: "Remote",
      status: "Full Time",
      itemT1:"Manager of Internal Sales Team",
      itemT2:"Manager of Operations Team",
      itemT3:"Corporate Partnerships",
      itemT4:"Prospecting & Sales Outreach",
    },
    {
      id: 2,
      title: "Affiliate Marketer",
      slug: "Affiliate-Marketer",
      dis1: `We appreciate your interest in joining the team at Ethereum Address Service (EAS) as an Affiliate Marketer. EAS is mapping the world’s addresses as tradable NFTs. With EAS, real-world addresses become transactable, able to generate revenue from their commercial application in Web3. We envision a future where every real-world address and point of interest has an associated EAS NFT. EAS serves as the platform to monetize and manage these new digital address rights and drive price appreciation for NFT buyers. As an Affiliate Marketer with EAS, you will gain valuable experience in the following areas:`,
      dis3: `The EAS Affiliate Marketer is a remote position and all required assignments are completed virtually. We DO NOT require physical attendance at an office location. There is no minimum requirement in terms of hours or weeks/months committed to the position. You are your own boss and free to come and go as you please. Bonuses will be paid on a success-only basis. To be eligible for this opportunity we would ask that you formally apply through the below link as well as sign-up as an affiliate on the EAS website at www.EASNFT.com. We look forward to meeting you and considering you for the EAS team. Best regards, The EAS Team`,
      dis5: `Best regards, `,
      dis6: `The EAS Team`,
      itemList1:` – Responsibilities will include marketing EAS NFTs to prospective buyers & crypto enthusiasts within your network as well as making new relationships.`,
      itemList2:` – Responsibilities will include assisting with the creation of EAS product materials to assist with buyer conversations.`,
      itemList3:` – Responsibilities will include review of sector and industry trends to assist the presentation and rollout of EAS products`,
      itemList4:` – Responsibilities will include research of target buyers and crafting outreach communications to initiate introductory dialogue with prospective buyers and crypto & NFT enthusiasts.`,
      date: "March 17, 20023",
      job: "Remote",
      status: "Full Time",
      itemT1:"Marketing",
      itemT2:"Presentation Materials",
      itemT3:"Sector and Industry Research",
      itemT4:"Prospecting & Sales Outreach",
    },
    {
      id: 3,
      title: "Marketing Internship",
      slug: "Marketing-Internship",
      dis1: `We appreciate your interest in joining the team at Ethereum Address Service (EAS) as a Marketing Intern. EAS is mapping the world’s addresses as tradable NFTs. With EAS, real-world addresses become transactable digital address rights designed to generate revenue from their commercial use in Web3 and the metaverse. We envision a future where every real-world address and point of interest has an associated EAS NFT. EAS serves as the platform to monetize and manage these new digital address rights and drive price appreciation for NFT buyers.`,
      dis2: `As a Marketing Intern with EAS, you will gain valuable experience in the following areas:`,
      dis3: `The EAS Marketing Internship is a remote position and all required assignments are completed virtually. We DO NOT require physical attendance at an office location. The internship is a non-paid position. To qualify as a full-time intern and use EAS as a reference on your resume, LinkedIn and track record, we require a minimum commitment of 12 weeks, with a minimum of 25 hours per week spent on intern assignments. Interns may become eligible for advancement within EAS dependent on performance and current corporate staffing needs.`,
      dis4: `To be eligible for this opportunity we would ask that you formally apply through the below link. We look forward to meeting you and considering you for the EAS team.`,
      dis5: `Best regards, `,
      dis6: `The EAS Team`,
      itemList1:` – Responsibilities will include creation of custom content to be distributed via EAS social media channels, including written, audio and video content on Twitter, Reddit, Discord and other platforms, blogging, presentation to on-campus clubs and crypto & NFT enthusiast groups, amongst other tasks.`,
      itemList2:`  – Responsibilities will include assisting with the creation of EAS company presentation materials and website copy.`,
      itemList3:` – Responsibilities will include review of sector and industry trends to assist the presentation and rollout of EAS products.`,
      itemList4:`– Responsibilities will include research of target buyers and crafting outreach communications to initiate introductory dialogue with prospective buyers and crypto & NFT enthusiasts.`,
      date: "March 17, 20023",
      job: "Remote",
      status: "Full Time",
      itemT1:"Marketing",
      itemT2:"Presentation Materials",
      itemT3:"Sector and Industry Research",
      itemT4:"Prospecting & Sales Outreach",
    },
  ];